/** @ignore */
export const CURRENT_CONTRACT_ARTIFACT_VERSION = 10; // add state type
/** @ignore */
export const SUPPORTED_MINIMUM_VERSION = 8;

/**
 * Application Binary Interface.
 * @category Artifact
 */
export interface ABI {
  contract: string;
  abi: Array<ABIEntity>;
}

/**
 * An Bitcoin Contract Artifact is a collection of files generated during the compilation of a smart contract.
 * It contains all the necessary metadata, code, and interfaces required to deploy, interact with,
 * and verify the contract on the Bitcoin blockchain. Artifacts are generated by `@opcat-labs/cli-opcat`.
 * @category Artifact
 */
export interface Artifact {
  /** version of artifact file */
  version: number;
  /** version of compiler used to produce this file */
  compilerVersion: string;
  /** build type, can be debug or release */
  buildType: string;
  /** name of the contract */
  contract: string;
  /** md5 of the contract source code */
  md5: string;
  /** all stateful properties defined in the contracts */
  stateProps: Array<ParamEntity>;
  /** the type of the `state` property used in the contracts */
  stateType?: string;
  /** all structures defined in the contracts, including dependent contracts */
  structs: Array<StructEntity>;
  /** all library defined in the contracts, including dependent contracts */
  library: Array<LibraryEntity>;
  /** all typealias defined in the contracts, including dependent contracts */
  alias: Array<AliasEntity>;
  /** ABI of the contract: interfaces of its public functions and constructor */
  abi: Array<ABIEntity>;
  /** locking script of the contract in hex format, including placeholders for constructor parameters */
  hex: string;
  /** relative file uri of the main contract source code file */
  file: string;
}

/**
 * @ignore
 */
export enum ABIEntityType {
  FUNCTION = 'function',
  CONSTRUCTOR = 'constructor',
}

/**
 * @ignore
 */
export type ParamEntity = {
  name: string;
  type: string;
};

/**
 * Application Binary Interface. A JSON array defining how to interact with the contract (e.g., functions, events, parameters).
 * Used by clients (like dApps) to encode/decode transactions and calls.
 * @category Artifact
 */
export interface ABIEntity {
  type: string;
  name?: string;
  params: Array<ParamEntity>;
  index?: number;
}

/**
 * @ignore
 */
export interface StructEntity {
  name: string;
  params: Array<ParamEntity>;
  genericTypes: Array<string>;
}

/**
 * @ignore
 */
export interface LibraryEntity extends StructEntity {
  properties: Array<ParamEntity>;
  /** the type of the `state` property used in the library */
  stateType?: string;
}

/**
 * @ignore
 */
export interface AliasEntity {
  name: string;
  type: string;
}

/**
 * @ignore
 */
export type ContractEntity = LibraryEntity;

/**
 * @ignore
 */
export interface StaticEntity {
  name: string;
  type: string;
  const: boolean;
  value?: any; // eslint-disable-line @typescript-eslint/no-explicit-any
}
