import {
  ByteString,
  prop,
  Sha256,
  SmartContractLib,
  toByteString,
} from '@opcat-labs/scrypt-ts-opcat'

/**
 * Canonical CAT20 Guard Script Hashes
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY!
 * This file is auto-generated by scripts/compile.ts during the compilation process.
 *
 * These hashes represent the canonical guard contract variants that are enforced
 * in the CAT20 contract constructor to prevent malicious guard substitution attacks.
 *
 * @category Constants
 * @onchain
 */
export class CAT20GuardVariants extends SmartContractLib {
  @prop()
  static readonly CANONICAL_GUARD_6_6_2: Sha256 = Sha256(
    toByteString('ca6368500575603ec5f442acca4e9384ea8c1b9462bafafacac5f123a45e6e8b')
  )

  @prop()
  static readonly CANONICAL_GUARD_6_6_4: Sha256 = Sha256(
    toByteString('3bea0ea6bd79d7bd4afb5c9ad81e32188697589626805d2555e5f5edeca4fd3d')
  )

  @prop()
  static readonly CANONICAL_GUARD_12_12_2: Sha256 = Sha256(
    toByteString('a87517548de1344a292d3391eb695f867d9ce8fa8fdbdff73af9fc7ec3b2abed')
  )

  @prop()
  static readonly CANONICAL_GUARD_12_12_4: Sha256 = Sha256(
    toByteString('f5b91b98b96efac89b0a94f72bb25e33ab062d6d7bdd1ecfd70b76b3854a99b7')
  )
}
