import {
  ByteString,
  prop,
  Sha256,
  SmartContractLib,
  toByteString,
} from '@opcat-labs/scrypt-ts-opcat'

/**
 * Canonical CAT20 Guard Script Hashes
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY!
 * This file is auto-generated by scripts/compile.ts during the compilation process.
 *
 * These hashes represent the canonical guard contract variants that are enforced
 * in the CAT20 contract constructor to prevent malicious guard substitution attacks.
 *
 * @category Constants
 * @onchain
 */
export class CAT20GuardVariants extends SmartContractLib {
  @prop()
  static readonly CANONICAL_GUARD_6_6_2: Sha256 = Sha256(
    toByteString('215e802b88723a1938425d947ed9f2ef46aa330cf99cc3aa96a2993a55e752f3')
  )

  @prop()
  static readonly CANONICAL_GUARD_6_6_4: Sha256 = Sha256(
    toByteString('fb659e2087db1bb23a19789b1d921b784435044454f4ea3668f8281ab514822b')
  )

  @prop()
  static readonly CANONICAL_GUARD_12_12_2: Sha256 = Sha256(
    toByteString('8d31a2cd8a91dff4cbd334e90b155ff560b7aa28c99167b4ac85f97f56e502d0')
  )

  @prop()
  static readonly CANONICAL_GUARD_12_12_4: Sha256 = Sha256(
    toByteString('999e18e74f9184ca9c332165610cef0f28c9207a78a6840ec7c7179b7873d5ce')
  )
}
