import {
  ByteString,
  prop,
  Sha256,
  SmartContractLib,
  toByteString,
} from '@opcat-labs/scrypt-ts-opcat'

/**
 * Canonical CAT20 Guard Script Hashes
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY!
 * This file is auto-generated by scripts/compile.ts during the compilation process.
 *
 * These hashes represent the canonical guard contract variants that are enforced
 * in the CAT20 contract constructor to prevent malicious guard substitution attacks.
 *
 * @category Constants
 * @onchain
 */
export class CAT20GuardVariants extends SmartContractLib {
  @prop()
  static readonly CANONICAL_GUARD_6_6_2: Sha256 = Sha256(
    toByteString('2abcd831081b4e802232579544bf542cb3b471941d04c9256ed6103715445a10')
  )

  @prop()
  static readonly CANONICAL_GUARD_6_6_4: Sha256 = Sha256(
    toByteString('fca6ff69a132b59cb9a612de495d3e5ffaa00e45ed27324021a837bc592dbe3b')
  )

  @prop()
  static readonly CANONICAL_GUARD_12_12_2: Sha256 = Sha256(
    toByteString('f2bf00644c5938caa0cf912fc003efcfd14d5dbf2cd1461712cd43851a54831d')
  )

  @prop()
  static readonly CANONICAL_GUARD_12_12_4: Sha256 = Sha256(
    toByteString('212e181d983f333ec62d1de1f59a522b5fbd05f0fbf11c8f973f96a6067ec545')
  )
}
