import {
  ByteString,
  prop,
  Sha256,
  SmartContractLib,
  toByteString,
} from '@opcat-labs/scrypt-ts-opcat'

/**
 * Canonical CAT721 Guard Script Hashes
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY!
 * This file is auto-generated by scripts/compile.ts during the compilation process.
 *
 * These hashes represent the canonical guard contract variants that are enforced
 * in the CAT721 contract constructor to prevent malicious guard substitution attacks.
 *
 * @category Constants
 * @onchain
 */
export class CAT721GuardVariants extends SmartContractLib {
  @prop()
  static readonly CANONICAL_GUARD_6_6_2: Sha256 = Sha256(
    toByteString('947dead5326bb5ebafebfae5eca10fb0344fe5300694bec98d0a42f5d865ea4e')
  )

  @prop()
  static readonly CANONICAL_GUARD_6_6_4: Sha256 = Sha256(
    toByteString('f644e40e404cca08738ec7d520b62b8c7349347d4354eca6e71e1c4243f34491')
  )

  @prop()
  static readonly CANONICAL_GUARD_12_12_2: Sha256 = Sha256(
    toByteString('d7594f0bd1f07969d366dbe0295bfc5ff9d12dffadb576c3d8fc15d694cedb39')
  )

  @prop()
  static readonly CANONICAL_GUARD_12_12_4: Sha256 = Sha256(
    toByteString('187665badd84fc4d09feb436bffbd63a09f46a23b7ccead3eba2ac1a4de9a4d7')
  )
}
