import {
  ByteString,
  prop,
  Sha256,
  SmartContractLib,
  toByteString,
} from '@opcat-labs/scrypt-ts-opcat'

/**
 * Canonical CAT721 Guard Script Hashes
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY!
 * This file is auto-generated by scripts/compile.ts during the compilation process.
 *
 * These hashes represent the canonical guard contract variants that are enforced
 * in the CAT721 contract constructor to prevent malicious guard substitution attacks.
 *
 * @category Constants
 * @onchain
 */
export class CAT721GuardVariants extends SmartContractLib {
  @prop()
  static readonly CANONICAL_GUARD_6_6_2: Sha256 = Sha256(
    toByteString('2933f841499dd31e1fe060690c84cda1380cabc064b751d21aad9ffbfefae4c6')
  )

  @prop()
  static readonly CANONICAL_GUARD_6_6_4: Sha256 = Sha256(
    toByteString('71f192d4a3e974932630af1997d88a9af2145dc4765c6f26f5da2eed8af88add')
  )

  @prop()
  static readonly CANONICAL_GUARD_12_12_2: Sha256 = Sha256(
    toByteString('21ef8b07f056077b19e0844a416d003d902ce0f017d21a341e057e6f762a30b3')
  )

  @prop()
  static readonly CANONICAL_GUARD_12_12_4: Sha256 = Sha256(
    toByteString('17e064cf6cb82bbe713c0c435fb1e2c84149d42689e537d5aeb8e45164bc2b10')
  )
}
