import { execSync } from 'child_process'
import fs from 'fs'
import path from 'path'
import { sha256 } from '@opcat-labs/scrypt-ts-opcat'
import { CAT20Guard_6_6_2 } from '../src/contracts/cat20/cat20Guard_6_6_2.js'
import { CAT20Guard_6_6_4 } from '../src/contracts/cat20/cat20Guard_6_6_4.js'
import { CAT20Guard_12_12_2 } from '../src/contracts/cat20/cat20Guard_12_12_2.js'
import { CAT20Guard_12_12_4 } from '../src/contracts/cat20/cat20Guard_12_12_4.js'
import { CAT721Guard_6_6_2 } from '../src/contracts/cat721/cat721Guard_6_6_2.js'
import { CAT721Guard_6_6_4 } from '../src/contracts/cat721/cat721Guard_6_6_4.js'
import { CAT721Guard_12_12_2 } from '../src/contracts/cat721/cat721Guard_12_12_2.js'
import { CAT721Guard_12_12_4 } from '../src/contracts/cat721/cat721Guard_12_12_4.js'

/**
 * Compilation script with guard hash validation
 *
 * Flow:
 * 1. compile() - First compilation to generate guard artifacts
 * 2. updateGuardVariants() - Load guard contracts, compute hashes using lockingScript, update guard variants files
 * 3. compile() - Second compilation with canonical guard hashes
 */

function compile() {
  console.log('🔨 Compiling contracts...')
  execSync('scrypt-cli-opcat compile', { stdio: 'inherit' })
  console.log('✅ Compilation complete\n')
}

function updateGuardVariants() {
  console.log('📝 Updating guard variants...\n')

  const artifactsDir = path.resolve(__dirname, '../artifacts')

  // ========== CAT20 Guard Variants ==========
  console.log('  Processing CAT20 guards:')

  // Read guard artifacts and load them
  const cat20GuardPaths = {
    guard_6_6_2: path.join(artifactsDir, 'cat20/cat20Guard_6_6_2.json'),
    guard_6_6_4: path.join(artifactsDir, 'cat20/cat20Guard_6_6_4.json'),
    guard_12_12_2: path.join(artifactsDir, 'cat20/cat20Guard_12_12_2.json'),
    guard_12_12_4: path.join(artifactsDir, 'cat20/cat20Guard_12_12_4.json'),
  }

  CAT20Guard_6_6_2.loadArtifact(JSON.parse(fs.readFileSync(cat20GuardPaths.guard_6_6_2, 'utf8')))
  CAT20Guard_6_6_4.loadArtifact(JSON.parse(fs.readFileSync(cat20GuardPaths.guard_6_6_4, 'utf8')))
  CAT20Guard_12_12_2.loadArtifact(JSON.parse(fs.readFileSync(cat20GuardPaths.guard_12_12_2, 'utf8')))
  CAT20Guard_12_12_4.loadArtifact(JSON.parse(fs.readFileSync(cat20GuardPaths.guard_12_12_4, 'utf8')))

  // Compute script hashes using lockingScript (same as ContractPeripheral.scriptHash)
  const cat20Hashes = {
    hash_6_6_2: sha256(new CAT20Guard_6_6_2().lockingScript.toHex()),
    hash_6_6_4: sha256(new CAT20Guard_6_6_4().lockingScript.toHex()),
    hash_12_12_2: sha256(new CAT20Guard_12_12_2().lockingScript.toHex()),
    hash_12_12_4: sha256(new CAT20Guard_12_12_4().lockingScript.toHex()),
  }

  console.log('    CAT20Guard_6_6_2  :', cat20Hashes.hash_6_6_2)
  console.log('    CAT20Guard_6_6_4  :', cat20Hashes.hash_6_6_4)
  console.log('    CAT20Guard_12_12_2:', cat20Hashes.hash_12_12_2)
  console.log('    CAT20Guard_12_12_4:', cat20Hashes.hash_12_12_4)

  const cat20GuardVariantsPath = path.resolve(__dirname, '../src/contracts/cat20/cat20GuardVariants.ts')
  const cat20FileContent = `import {
  ByteString,
  prop,
  Sha256,
  SmartContractLib,
  toByteString,
} from '@opcat-labs/scrypt-ts-opcat'

/**
 * Canonical CAT20 Guard Script Hashes
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY!
 * This file is auto-generated by scripts/compile.ts during the compilation process.
 *
 * These hashes represent the canonical guard contract variants that are enforced
 * in the CAT20 contract constructor to prevent malicious guard substitution attacks.
 *
 * @category Constants
 * @onchain
 */
export class CAT20GuardVariants extends SmartContractLib {
  @prop()
  static readonly CANONICAL_GUARD_6_6_2: Sha256 = Sha256(
    toByteString('${cat20Hashes.hash_6_6_2}')
  )

  @prop()
  static readonly CANONICAL_GUARD_6_6_4: Sha256 = Sha256(
    toByteString('${cat20Hashes.hash_6_6_4}')
  )

  @prop()
  static readonly CANONICAL_GUARD_12_12_2: Sha256 = Sha256(
    toByteString('${cat20Hashes.hash_12_12_2}')
  )

  @prop()
  static readonly CANONICAL_GUARD_12_12_4: Sha256 = Sha256(
    toByteString('${cat20Hashes.hash_12_12_4}')
  )
}
`
  fs.writeFileSync(cat20GuardVariantsPath, cat20FileContent, 'utf8')
  console.log('    ✅ Updated cat20GuardVariants.ts\n')

  // ========== CAT721 Guard Variants ==========
  console.log('  Processing CAT721 guards:')

  // Read guard artifacts and load them
  const cat721GuardPaths = {
    guard_6_6_2: path.join(artifactsDir, 'cat721/cat721Guard_6_6_2.json'),
    guard_6_6_4: path.join(artifactsDir, 'cat721/cat721Guard_6_6_4.json'),
    guard_12_12_2: path.join(artifactsDir, 'cat721/cat721Guard_12_12_2.json'),
    guard_12_12_4: path.join(artifactsDir, 'cat721/cat721Guard_12_12_4.json'),
  }

  CAT721Guard_6_6_2.loadArtifact(JSON.parse(fs.readFileSync(cat721GuardPaths.guard_6_6_2, 'utf8')))
  CAT721Guard_6_6_4.loadArtifact(JSON.parse(fs.readFileSync(cat721GuardPaths.guard_6_6_4, 'utf8')))
  CAT721Guard_12_12_2.loadArtifact(JSON.parse(fs.readFileSync(cat721GuardPaths.guard_12_12_2, 'utf8')))
  CAT721Guard_12_12_4.loadArtifact(JSON.parse(fs.readFileSync(cat721GuardPaths.guard_12_12_4, 'utf8')))

  // Compute script hashes using lockingScript (same as ContractPeripheral.scriptHash)
  const cat721Hashes = {
    hash_6_6_2: sha256(new CAT721Guard_6_6_2().lockingScript.toHex()),
    hash_6_6_4: sha256(new CAT721Guard_6_6_4().lockingScript.toHex()),
    hash_12_12_2: sha256(new CAT721Guard_12_12_2().lockingScript.toHex()),
    hash_12_12_4: sha256(new CAT721Guard_12_12_4().lockingScript.toHex()),
  }

  console.log('    CAT721Guard_6_6_2  :', cat721Hashes.hash_6_6_2)
  console.log('    CAT721Guard_6_6_4  :', cat721Hashes.hash_6_6_4)
  console.log('    CAT721Guard_12_12_2:', cat721Hashes.hash_12_12_2)
  console.log('    CAT721Guard_12_12_4:', cat721Hashes.hash_12_12_4)

  const cat721GuardVariantsPath = path.resolve(__dirname, '../src/contracts/cat721/cat721GuardVariants.ts')
  const cat721FileContent = `import {
  ByteString,
  prop,
  Sha256,
  SmartContractLib,
  toByteString,
} from '@opcat-labs/scrypt-ts-opcat'

/**
 * Canonical CAT721 Guard Script Hashes
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY!
 * This file is auto-generated by scripts/compile.ts during the compilation process.
 *
 * These hashes represent the canonical guard contract variants that are enforced
 * in the CAT721 contract constructor to prevent malicious guard substitution attacks.
 *
 * @category Constants
 * @onchain
 */
export class CAT721GuardVariants extends SmartContractLib {
  @prop()
  static readonly CANONICAL_GUARD_6_6_2: Sha256 = Sha256(
    toByteString('${cat721Hashes.hash_6_6_2}')
  )

  @prop()
  static readonly CANONICAL_GUARD_6_6_4: Sha256 = Sha256(
    toByteString('${cat721Hashes.hash_6_6_4}')
  )

  @prop()
  static readonly CANONICAL_GUARD_12_12_2: Sha256 = Sha256(
    toByteString('${cat721Hashes.hash_12_12_2}')
  )

  @prop()
  static readonly CANONICAL_GUARD_12_12_4: Sha256 = Sha256(
    toByteString('${cat721Hashes.hash_12_12_4}')
  )
}
`
  fs.writeFileSync(cat721GuardVariantsPath, cat721FileContent, 'utf8')
  console.log('    ✅ Updated cat721GuardVariants.ts\n')
}


async function main() {
  console.log('═══════════════════════════════════════════════════════════')
  console.log('  CAT20/CAT721 Compilation with Guard Hash Validation')
  console.log('═══════════════════════════════════════════════════════════\n')

  console.log('Phase 1: Initial compilation\n')
  compile()

  console.log('Phase 2: Update guard variants\n')
  updateGuardVariants()

  console.log('Phase 3: Recompile with canonical guard hashes\n')
  compile()

  console.log('═══════════════════════════════════════════════════════════')
  console.log('  ✅ Compilation Complete!')
  console.log('═══════════════════════════════════════════════════════════')
}

main().catch(err => {
  console.error('\n❌ Compilation failed:', err.message)
  process.exit(1)
})
